---
title: "Estimación estadística del Ancho de Banda Efectivo"
author: "Natalia Clivio"
date: '2015'
output: word_document
header-includes: -\usepackage[utf8]{inputenc} - \usepackage{dcolumn}
---



Calculando el punto crítico **(s,t)**

````{r}
mpeg<-read.csv("C:/Users/NataliaA/Documents/Maestria/Tráfico L3/MPEG/Verbose_StarWarsIV.dat",header=FALSE,sep="",na.strings="NA",dec=".",skip=2)

setmpeg<-data.frame(No=mpeg$V1,Type=mpeg$V2,"time_ms"=mpeg$V3,byte=mpeg$V4)
Iset<-subset(setmpeg,Type=="I")

a<-subset(Iset,byte>4000)
l<-2209   #Q Transiciones del estado 0 a h (ON)
u<-7499  #Q Transiciones que salen del estado 0 (OFF)
h<-(7913*8)/1000  #Pico de la Traza (Kbps) 7913

````

````{r}
pi1<-l/(l+u)
pi2<-u/(l+u)

space<-seq(length=100, from=1, to=100) 
time<-seq(length=100, from=1, to=30) 
s<-log10(space)
t<-log10(time)

Bw<-function(t,s) {(1/s)*log10(pi2+(exp((h*s))*pi1))}   
z<-outer(t,s,Bw) # La función outer evalua la función Bw en cada punto (si,tj)

persp(t,s,z,theta=20,phi=-0,col ="orange"
      ,ticktype ="detailed",xlab="t (ms)",ylab="s",zlab="(s,t)") 

````{r}

set<-read.csv("C:/Users/NataliaA/Documents/Maestria/Tráfico L3/VoIP/Subs_Voip.txt",header=TRUE,sep=",",na.strings="NA",dec=".")
set30<-sample(set$MAC.Voip,size =30,replace =FALSE )
set30
