---
title: "Simulaciones y Resultados"
author: "Natalia Clivio"
date: '2015'
output: word_document
---
#Análisis de Trazas Reales

##Tráfico de Internet Residencial

```{r}
library(ggplot2)

data<-read.csv("C:/Users/NataliaA/Documents/Maestria/Tráfico L3/Datos/Bitrate+for+CM_week.csv",
                  header=TRUE,sep=";",na.strings="NA",dec=".")

dataset<-data.frame(data[1],data[2],data[3],data[4])

d<-as.character(dataset$Date)
t<-as.character(dataset$Time)
time<-data.frame(d,t)
time<-paste(time$d,time$t,sep=" ")
Date<-strptime(time,"%m/%d/%Y %H:%M")

DS_data<-as.character(dataset$DS.bps)
DS_Kbps<-as.numeric(DS_data)/1000

DS<-data.frame("Date"=Date,"DS_Kbps"=DS_Kbps)

plot(DS,type="l",col="blue",xlab="time (h)",ylab="Downstream (Kbps)",
     main="Tráfico de un usuario residencial 6 Mbps")
abline(v=NULL,h=2000,lty=3,col="gray")
abline(v=NULL,h=4000,lty=3,col="gray")
abline(v=NULL,h=6000,lty=3,col="gray")
````

Los parámetros de la traza son:

````{r}
summary(DS$DS_Kbps)

C<-
B<-
u<-417.8 #Kbps
var<-
H<-
````

